##### FORMAT #####
# blocks:
#   BLOCK_NAME:
#     drops:
# The first amount is for the minimum, second is for the maximum
#       - ITEM_NAME;PERCENT CHANCE;AMOUNT-AMOUNT
#       - ITEM_NAME;PERCENT CHANCE;AMOUNT-AMOUNT
#       - ITEM_NAME;PERCENT CHANCE;AMOUNT-AMOUNT
#       - ITEM_NAME;PERCENT CHANCE;AMOUNT-AMOUNT
#  ANOTHER_BLOCK:
#     drops:
#       - ITEM_NAME;PERCENT CHANCE;AMOUNT-AMOUNT
# this can repeat as much as you want, there is no limit
blocks:
  GRASS:
    drops:
      - DIAMOND_ORE;94.9;10-20
      - IRON_INGOT;5.1;3-7
  STONE:
    drops:
      - DIAMOND;50;10-10
      - ANVIL;50;5-5