# block to replace
custom-drop-block: 'STONE'
# total value must equal 10,000
# block name must be capital
custom-drop-values:
  - STONE;6000
  - COAL;1700
  - IRON_INGOT;1200
  - GOLD_INGOT;800
  - DIAMOND;200
  - EMERALD;100