# block to replace
custom-drop-block: 'STONE'
custom-drop-message: '&eYou mined &c{0}&e.'
# total value must equal 10,000
# block name must be capital
custom-drop-values:
  - COBBLESTONE;7700
  - COAL;1000
  - IRON_ORE;750
  - GOLD_ORE;400
  - DIAMOND;100
  - EMERALD;50
send-message-values:
  - IRON_ORE
  - GOLD_ORE
  - DIAMOND
  - EMERALD