##### FORMAT #####
# blocks:
#   BLOCK_NAME:
#     drops:
#       - ITEM_NAME;PERCENT CHANCE;AMOUNT
#       - ITEM_NAME;PERCENT CHANCE;AMOUNT
#       - ITEM_NAME;PERCENT CHANCE;AMOUNT
#       - ITEM_NAME;PERCENT CHANCE;AMOUNT
#  ANOTHER_BLOCK:
#     drops:
#       - ITEM_NAME;PERCENT CHANCE;AMOUNT
# this can repeat as much as you want, there is no limit
blocks:
  GRASS:
    drops:
      - DIAMOND_ORE;94.9;10
      - IRON_INGOT;5.1;5
  STONE:
    drops:
      - DIAMOND;50;10
      - ANVIL;50;5